"""
===============================================================================
NeuroEng Voltage Transient Processor - Module - Global Defaults & Config
===============================================================================

Author:     Ifra Ilyas Ansari
Created:    2025-10-17
Modified:   2025-10-27
Code:       VT_Module_Py_GlobalSettings.py
Version:    v1.1.0

DESCRIPTION
---------------------------
- Central configuration module for the VT processing pipeline.
- Stores global constants (system info, default Tektronix channel maps).
- Defines a "Single Source of Truth" for canonical column names (e.g., "Time (µs)")
  and plot labels used across all scripts.
- Applies a global matplotlib.rcParams theme for consistent plot styling.

NOTE
---------------------------
- Processing functions (like standardization) have been moved to 
  VT_Module_Py_Processing.py.
- System functions (like paths) have been moved to VT_Module_Py_System.py.

===============================================================================
"""
#==============================================================================
# 📦 Imports
#==============================================================================
from __future__ import annotations    # Must be the first non-comment line
import platform
import getpass
from matplotlib import rcParams

#==============================================================================
# 💻 System Info (Basic Hardware/User Info)
#==============================================================================
# Note: More detailed system info/paths are in VT_Module_Py_System.py
DICT_SYSTEM_INFO = {
    "system": platform.system(),
    "release": platform.release(),
    "python_version": platform.python_version(),
    "user": getpass.getuser(),
}

#==============================================================================
# 🔌 Tektronix Oscilloscope Channel Map (Default)
#==============================================================================
# These are the *default* assumptions if explicit names aren't found.
DICT_TEK_CHANNEL_MAP = {
    "TIME":    "TIME",    # Assumes a column named 'TIME' exists if specific units aren't found.
    "VOLTAGE": "CH1",     # Default assumption: Voltage is on Channel 1
    "CURRENT": "CH2",     # Default assumption: Current is on Channel 2
}
# ❗ IMPORTANT: You might need to adjust VOLTAGE/CURRENT if your setup differs.

#==============================================================================
# 🏷️ Canonical Column Names & Plot Labels (Single Source of Truth)
#==============================================================================
# These define the standard column names used *after* processing/standardization
# and are also used as default plot axis labels.
CANON_TIME_UNIT = "µs"
CANON_TIME = f"Time ({CANON_TIME_UNIT})"
CANON_VOLT = "Voltage (V)"
CANON_CURR = "Current (A)"

# --- Aliases for convenience in main scripts ---
xcol_t = CANON_TIME
ycol_v = CANON_VOLT
ycol_i = CANON_CURR

# --- Dictionary primarily for easy plot labeling ---
DICT_AXIS_LABELS = {
    "TIME":    CANON_TIME,
    "VOLTAGE": CANON_VOLT,
    "CURRENT": CANON_CURR,
}

#==============================================================================
# 🎨 Global Plot Style (matplotlib.rcParams)
#==============================================================================
# Apply a consistent theme for all plots generated by the pipeline.
rcParams.update({
    
    # --- 🖋️ Font & Layout ---
    "font.family": "Arial",              # [Arial, Times New Roman, Helvetica, DejaVu Sans]
    "font.size": 10,                     # [Integer = 8, 10, 12] Base font size
    "font.weight": "normal",             # [normal, bold, light", medium, heavy]    

    # --- 📐 Axes Style ---
    "axes.labelsize": 12,                # [Integer] Axis labels (e.g., "Voltage (V)")
    "axes.labelweight": "bold",          # [normal, bold]
    "axes.labelpad": 4,                  # [Integer] Spacing between axis label and ticks

    "axes.titlesize": 14,                # [Integer] Plot titles (e.g., "Voltage vs Time")
    "axes.titleweight": "bold",          # [normal, bold]
    "axes.titlepad": 10,                 # [Integer/Float] Spacing between title and plot area

    "axes.linewidth": 1.0,               # Thickness of axis lines/spines [Float = 0.8, 1.0, 1.5] 
    "axes.facecolor": "white",           # Background color of plot area [white, lightgray, #f0f0f0]
    "axes.grid": True,                   # Grid lines [True/False] 
    # If axes.grid = True    
    "grid.color": "#dddddd",             # Light gray grid lines [#cccccc, lightgray]
    "grid.linestyle": ":",               # Dotted grid lines [ - or -- or : or -. ]
    "grid.linewidth": 0.5,               # [Float = 0.3, 0.5, 1.0]
 
    # --- 📏 Tick Style ---
    "xtick.labelsize": 10,              # [Integer] Tick label font size (numbers on axes)
    "ytick.labelsize": 10,              # [Integer]
    "xtick.major.width": 1,             # [Float] Thickness of major ticks
    "ytick.major.width": 1,             # [Float]
    "xtick.direction": "inout",         # [in, out, inout] Tick pointing direction
    "ytick.direction": "inout",         # [in, out, inout]
    "xtick.major.size": 6,              # Major tick length
    "ytick.major.size": 6,
    "xtick.minor.size": 3,              # Minor tick length
    "ytick.minor.size": 3,
    "xtick.minor.width": 0.8,           # Minor tick width
    "ytick.minor.width": 0.8,
    "xtick.minor.visible": True,        # Auto-show minor ticks
    "ytick.minor.visible": True,
    "yaxis.labellocation": "center",
    
    # --- 🗂️ Legend Style ---
    # Note: place_legend_left in PlotHelpers overrides some of these
    "legend.title_fontsize": 10,         # [Integer]
    "legend.fontsize": 9,                # [Integer]
    "legend.loc": "upper left",          # [best, left, right, center, lower/upper/center left/right/center] Default if unspecified
    "legend.frameon": False,             # Show legend box [True or False]
    # If legend.frameon = True
    "legend.edgecolor": "gray",          # Legend box border color 
    "legend.fancybox": True,             # Rounded box corners [True/False] 
    "legend.borderpad": 0.4,             # Space around legend box [Float] 

    # --- 📈 Line Style ---
    "lines.linewidth": 1.0,              # Default line thickness # [Float = 1.0, 2.0]

    # --- 🖼️ Figure Layout ---
    "figure.figsize": (7.2, 4.0),        # Default figure size in inches (Width, Height) 
    "figure.autolayout": False,          # True = avoids clipping axis labels 
    "figure.constrained_layout.use": True, # Automatically adjust spacing to prevent overlap

    # --- 💾 Save Style ---
    "savefig.dpi": 300,                  # Output resolution for saved figures [100, 200, 300]
    "savefig.transparent": False,        # Default to non-transparent background
    "savefig.bbox": "tight",             # Crop saved figure tightly around content
    
    # --- 🔠 Text Rendering ---
    "text.usetex": False,                # True ( LaTeX: pretty, slow) / False (system fonts: faster)
})

#==============================================================================
# 📤 Module Exports
#==============================================================================
# Define what gets imported by 'from VT_Module_Py_GlobalSettings import *'

__all__ = [
    # Constants
    "DICT_SYSTEM_INFO",
    "DICT_TEK_CHANNEL_MAP",
    "CANON_TIME_UNIT",
    "CANON_TIME",
    "CANON_VOLT",
    "CANON_CURR",
    # Aliases
    "xcol_t",
    "ycol_v",
    "ycol_i",
    # Dictionaries
    "DICT_AXIS_LABELS",
    # Note: rcParams are applied automatically on import, no need to export
]